---
- name: install epel-release for CentOS
  block:
  - name: enable codeready builder (crb)
    shell: >
      dnf config-manager --set-enabled crb
  - name: install epel-release packages
    yum:
      name: 
        - epel-release
        - epel-next-release
      state: present
  when: ansible_distribution == "CentOS"

- name: install epel-release for Enterprise Linux
  block:
  - name: enable RH repos
    rhsm_repository:
      name: codeready-builder-for-rhel-9-$(arch)-rpms
      state: enabled
  - name:
    yum:
      name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
      state: present
  when: ansible_distribution == "RedHat"


