---
# handlers for install_openvpn role
- name: restart openvpn service
  service:
    name: "{{ item.service }}"
    enabled: yes
    state: restarted
  loop: "{{ vpn_client }}"
  when: item.family == ansible_os_family
