---
# handlers for install_openvpn role
- name: restart openvpn service
  service:
    name: "{{ item.service }}"
    enabled: yes
    state: restarted
  loop: "{{ vpn_client_vars }}"
  when: item.family == ansible_os_family

- name: restart firewalld service
  service:
    name: firewalld
    enabled: yes
    state: restarted

- name: restart ufw service
  service:
    name: ufw
    enabled: yes
    state: restarted
