---
# handlers for install_openvpn role
- name: restart openvpn service
  service:
    name: "{{ item.name }}"
    enabled: yes
    state: restarted
  loop: "{{ service }}"
  when: item.family == ansible_os_family
